"""enforce_non_nullable_userid

Revision ID: 507b8de6c20a
Revises: e8810a495875
Create Date: 2026-01-02 11:47:54.479331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507b8de6c20a'
down_revision = 'e8810a495875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
