"""empty message

Revision ID: e8810a495875
Revises: 3116c4eaab6a
Create Date: 2026-01-02 00:36:55.520486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8810a495875'
down_revision = '3116c4eaab6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        op.execute("UPDATE api_request_log SET user_id = 1 WHERE user_id IS NULL")
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_request_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
